"""medicine_id column added in grns, purchase_orders table

Revision ID: 2105154046fe
Revises: 4f91a490e6fa
Create Date: 2022-02-15 11:01:56.781623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2105154046fe'
down_revision = '4f91a490e6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grns', sa.Column('manufacture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grns', 'manufacturers', ['manufacture_id'], ['id'], ondelete='SET NULL')
    op.add_column('purchase_orders', sa.Column('manufacturer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'manufacturers', ['manufacturer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'manufacturer_id')
    op.drop_constraint(None, 'grns', type_='foreignkey')
    op.drop_column('grns', 'manufacture_id')
    # ### end Alembic commands ###
