"""separate table for pharmacy and address table deleted

Revision ID: 03f469dd3206
Revises: 2c74ed5d1c10
Create Date: 2022-02-20 15:05:33.347829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03f469dd3206'
down_revision = '2c74ed5d1c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    op.add_column('customers', sa.Column('location', sa.String(length=225), nullable=True))
    op.add_column('pharmacies', sa.Column('area', sa.String(length=100), nullable=False))
    op.add_column('pharmacies', sa.Column('sub_district', sa.String(length=50), nullable=False))
    op.add_column('pharmacies', sa.Column('district', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'pharmacies', ['trade_license'])
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_constraint(None, 'pharmacies', type_='unique')
    op.drop_column('pharmacies', 'district')
    op.drop_column('pharmacies', 'sub_district')
    op.drop_column('pharmacies', 'area')
    op.drop_column('customers', 'location')
    op.create_table('addresses',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('area', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('district', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('sub_district', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='addresses_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='addresses_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
