"""gross_margin removed from stocks table Feb 23

Revision ID: 7f6985709bc5
Revises: fe5c470a0d09
Create Date: 2022-02-23 11:03:17.137106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f6985709bc5'
down_revision = 'fe5c470a0d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'gross_margin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('gross_margin', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
