"""column name changed on manufacture to manufacturer in grns

Revision ID: a4b0cd0c4763
Revises: 2105154046fe
Create Date: 2022-02-16 11:31:22.575851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4b0cd0c4763'
down_revision = '2105154046fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grns', sa.Column('manufacturer_id', sa.Integer(), nullable=True))
    op.drop_constraint('grns_ibfk_3', 'grns', type_='foreignkey')
    op.create_foreign_key(None, 'grns', 'manufacturers', ['manufacturer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('grns', 'manufacture_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grns', sa.Column('manufacture_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grns', type_='foreignkey')
    op.create_foreign_key('grns_ibfk_3', 'grns', 'manufacturers', ['manufacture_id'], ['id'], ondelete='SET NULL')
    op.drop_column('grns', 'manufacturer_id')
    # ### end Alembic commands ###
