"""manufacturer_id foreignkey ondelete cascade in medicines

Revision ID: e4e5f2697188
Revises: 3832389191a4
Create Date: 2022-02-10 11:06:44.580132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e5f2697188'
down_revision = '3832389191a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('medicines_ibfk_1', 'medicines', type_='foreignkey')
    op.create_foreign_key(None, 'medicines', 'manufacturers', ['manufacturer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medicines', type_='foreignkey')
    op.create_foreign_key('medicines_ibfk_1', 'medicines', 'manufacturers', ['manufacturer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
